#!/usr/bin/env python3
"""
Inspect a live Solr instance and generate a migration report.

Connects to Solr, pulls schema/metrics/index stats via SolrInspector,
runs the full skill inspection pipeline, and writes the migration
report to a markdown file.

Usage:
    python inspect_and_report.py [SOLR_URL] [COLLECTION] [OUTPUT_FILE]
    python inspect_and_report.py                                          # defaults
    python inspect_and_report.py http://localhost:38983 ecommerce report.md
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPTS_DIR = os.path.join(SCRIPT_DIR, "..", "..", "scripts")
sys.path.insert(0, SCRIPTS_DIR)

from skill import SolrToOpenSearchMigrationSkill
from solr_inspector import SolrInspector
from storage import InMemoryStorage


def main():
    solr_url = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:38983"
    collection = sys.argv[2] if len(sys.argv) > 2 else "ecommerce"
    output_file = sys.argv[3] if len(sys.argv) > 3 else os.path.join(
        SCRIPT_DIR, "migration-report.md"
    )
    session_id = "live-demo"

    print(f"Connecting to Solr at {solr_url}...")
    inspector = SolrInspector(solr_url)

    # --- Gather live data ---
    print("Fetching system info...")
    system = inspector.get_system_info()
    solr_version = system.get("lucene", {}).get("solr-spec-version", "?")
    print(f"  Solr version: {solr_version}")

    print(f"Fetching schema for '{collection}'...")
    schema = inspector.get_schema(collection)
    fields = schema.get("schema", {}).get("fields", [])
    field_types = schema.get("schema", {}).get("fieldTypes", [])
    copy_fields = schema.get("schema", {}).get("copyFields", [])
    print(f"  Fields: {len(fields)}, Types: {len(field_types)}, CopyFields: {len(copy_fields)}")

    print("Fetching index stats...")
    luke = inspector.get_luke(collection)
    num_docs = luke.get("index", {}).get("numDocs", 0)
    print(f"  Documents: {num_docs}")

    print("Fetching metrics...")
    metrics = inspector.get_metrics("core")

    print("Fetching query handler stats...")
    # Fetch all categories (omit cat parameter) for comprehensive handler stats
    mbeans = inspector._get_json(
        f"/solr/{collection}/admin/mbeans?stats=true"
    )

    # --- Extract handler stats for the report ---
    handler_summary = _extract_handler_stats(mbeans)

    # --- Run skill pipeline ---
    print("\nRunning migration advisor pipeline...")
    skill = SolrToOpenSearchMigrationSkill(storage=InMemoryStorage())

    # Inspect Solr (stores facts in session)
    result = skill.inspect_solr(solr_url, collection, session_id)
    print(f"  {result}")

    # Add client integration facts from handler analysis
    state = skill._storage.load(session_id)
    if handler_summary:
        state.set_fact("solr_handler_stats", handler_summary)
    skill._storage.save(state)

    # Generate the report
    print("Generating migration report...")
    report = skill.generate_report(session_id)

    # --- Build the full output ---
    output_lines = [
        f"<!-- Generated by inspect_and_report.py -->",
        f"<!-- Source: {solr_url}/solr/{collection} -->",
        f"<!-- Solr version: {solr_version} -->",
        f"<!-- Documents: {num_docs} -->",
        f"<!-- Generated: {_now()} -->",
        "",
        report,
    ]

    # Append Solr inspection summary
    output_lines.extend([
        "",
        "---",
        "",
        "## Solr Instance Summary",
        "",
        f"- **Solr URL:** {solr_url}",
        f"- **Collection:** {collection}",
        f"- **Solr Version:** {solr_version}",
        f"- **Documents:** {num_docs:,}",
        f"- **Fields:** {len(fields)}",
        f"- **Field Types:** {len(field_types)}",
        f"- **Copy Fields:** {len(copy_fields)}",
        "",
    ])

    # Append handler stats if available
    if handler_summary:
        output_lines.extend([
            "## Query Handler Stats",
            "",
            "| Handler | Requests | Errors | Avg Time (ms) |",
            "|---|---|---|---|",
        ])
        for h in handler_summary:
            output_lines.append(
                f"| {h['handler']} | {h['requests']:,} | {h['errors']:,} | {h['avg_time']:.1f} |"
            )
        output_lines.append("")

    # Append the OpenSearch mapping
    state = skill._storage.load(session_id)
    mapping = state.get_fact("opensearch_mapping")
    if mapping:
        output_lines.extend([
            "## Generated OpenSearch Mapping",
            "",
            "```json",
            json.dumps(mapping, indent=2),
            "```",
            "",
        ])

    # Write output
    with open(output_file, "w") as f:
        f.write("\n".join(output_lines))

    print(f"\nReport saved to: {output_file}")
    print(f"  {len(output_lines)} lines, {os.path.getsize(output_file):,} bytes")

    return output_file


def _extract_handler_stats(mbeans):
    """Extract per-handler request stats from MBeans response."""
    handlers = []
    solr_mbeans = mbeans.get("solr-mbeans", [])

    # MBeans response is alternating: [category_name, {handlers}, ...]
    for i in range(0, len(solr_mbeans) - 1, 2):
        if not isinstance(solr_mbeans[i + 1], dict):
            continue
        for name, info in solr_mbeans[i + 1].items():
            if not isinstance(info, dict):
                continue
            stats = info.get("stats")
            if not isinstance(stats, dict):
                continue
            # Solr 8 prefixes stat keys: "QUERYHANDLER./select.requests"
            # Find the requests key by suffix match
            requests = 0
            errors = 0
            total_time = 0
            for key, val in stats.items():
                if key.endswith(".requests") and isinstance(val, (int, float)):
                    requests = int(val)
                elif key.endswith(".errors.count") and isinstance(val, (int, float)):
                    errors = int(val)
                elif key.endswith(".totalTime") and not key.endswith(".distrib.totalTime"):
                    if key.count(".") == 2 and isinstance(val, (int, float)):
                        total_time = float(val)
            if requests == 0:
                continue
            avg_time = (total_time / requests / 1_000_000) if requests > 0 else 0
            handlers.append({
                "handler": name,
                "requests": requests,
                "errors": errors,
                "avg_time": avg_time,
            })

    handlers.sort(key=lambda h: h["requests"], reverse=True)
    return handlers


def _now():
    """UTC timestamp string."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


if __name__ == "__main__":
    main()
