#!/usr/bin/env bash
# ============================================================================
# Migration Report Demo
# ============================================================================
# Feeds a Solr schema through the skill and produces a standalone
# migration report as a Markdown file.
#
# Usage:
#   bash run_report_demo.sh                          # uses built-in sample schema
#   bash run_report_demo.sh /path/to/schema.xml      # uses your schema
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCRIPTS_DIR="$SKILL_DIR/scripts"
REPORT_FILE="$SCRIPT_DIR/migration-report.md"

# Use provided schema or built-in sample
if [ $# -ge 1 ] && [ -f "$1" ]; then
    SCHEMA_XML=$(cat "$1")
    SCHEMA_SOURCE="$1"
else
    SCHEMA_SOURCE="built-in sample (techproducts-like)"
    SCHEMA_XML='<schema name="techproducts" version="1.6">
  <fieldType name="string" class="solr.StrField" sortMissingLast="true"/>
  <fieldType name="pint" class="solr.IntPointField" docValues="true"/>
  <fieldType name="text_general" class="solr.TextField" positionIncrementGap="100">
    <analyzer type="index">
      <tokenizer class="solr.StandardTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
    </analyzer>
    <analyzer type="query">
      <tokenizer class="solr.StandardTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
    </analyzer>
  </fieldType>
  <fieldType name="location" class="solr.LatLonPointSpatialField" docValues="true"/>
  <fieldType name="pdate" class="solr.DatePointField" docValues="true"/>
  <fieldType name="boolean" class="solr.BoolField" sortMissingLast="true"/>
  <fieldType name="pfloat" class="solr.FloatPointField" docValues="true"/>

  <field name="id" type="string" indexed="true" stored="true" required="true"/>
  <field name="name" type="text_general" indexed="true" stored="true"/>
  <field name="price" type="pfloat" indexed="true" stored="true"/>
  <field name="inStock" type="boolean" indexed="true" stored="true"/>
  <field name="cat" type="string" indexed="true" stored="true" multiValued="true"/>
  <field name="manu" type="string" indexed="true" stored="true"/>
  <field name="store" type="location" indexed="true" stored="true"/>
  <field name="last_modified" type="pdate" indexed="true" stored="true"/>

  <copyField source="name" dest="name_sort"/>
  <copyField source="cat" dest="text"/>
</schema>'
fi

echo "=== Migration Report Demo ==="
echo "Schema source: $SCHEMA_SOURCE"
echo ""

# Run the skill
python3 -c "
import sys, json
sys.path.insert(0, '$SCRIPTS_DIR')
from skill import SolrToOpenSearchMigrationSkill
from storage import InMemoryStorage

skill = SolrToOpenSearchMigrationSkill(storage=InMemoryStorage())
schema_xml = '''$SCHEMA_XML'''

# Step 1: Convert schema
response = skill.handle_message('Please convert this schema: ' + schema_xml, 'report-demo')
print('--- Schema Conversion ---')
print(response)
print()

# Step 2: Generate report
report = skill.generate_report('report-demo')
print('--- Migration Report ---')
print(report)

# Save report to file
with open('$REPORT_FILE', 'w') as f:
    f.write('<!-- Generated by run_report_demo.sh -->\n')
    f.write('<!-- Schema source: $SCHEMA_SOURCE -->\n\n')
    f.write(report)
    f.write('\n\n---\n\n## OpenSearch Mapping\n\n')
    # Extract just the mapping JSON from the conversion response
    state = skill._storage.load('report-demo')
    if state and state.get_fact('schema_migrated'):
        mapping = skill.convert_schema_xml(schema_xml)
        f.write('\`\`\`json\n' + json.dumps(json.loads(mapping), indent=2) + '\n\`\`\`\n')
"

echo ""
echo "Report saved to: $REPORT_FILE"
echo "============================================================"
